package Interpreter.ProgramTree.Enums;

public enum NodeType {
    PROGRAM,
    FUNC_DEF,
    FUNC_DEF_PARAM,
    FUNC_DEF_PARAMS,
    BODY,
    IF_STMT,
    ELSEIF_BLOCK,
    ELSE_BLOCK,
    WHILE_LOOP,
    FUNC_CALL,
    FUNC_CALL_PARAMS,
    VAR_DECL,
    ASSIGNMENT,
    RETURN_STATEMENT,
    OPERATOR,
    TYPE,
    BOOL,
    NUMBER,
    STRING,
    FUNC_REF,
    VAR_REF,
}
